module.exports = {
  apiKey: process.env.LOCATIONIQ_API_KEY, // Make sure to set the LOCATIONIQ_API_KEY in .env
  baseUrl: "https://us1.locationiq.com/v1/nearby.php",
  CATEGORIES: [
    "cafe",
    "restaurant",
    "natural:beach",
    "pub",
    "cinema",
    "gym",
    "place_of_worship",
    "park",
    "stadium",
    // "amenity:ice_cream",
    // "tourism:museum",
    // "amenity:cinema",
    // "shop:mall",
    // "tourism:aquarium",
    // "amenity:library",
    // "leisure:sports_centre",
    // "tourism:gallery",
    // "amenity:food_court",
    // "tourism:zoo",
    // "historic:castle",
    // "tourism:theme_park",
    // "amenity:pub",
    // "leisure:swimming_pool",
    // "sport:climbing",
    // "tourism:viewpoint",
  ],
};
